version: '3.8'

services:
  db:
    image: postgres:15
    container_name: job-navigator-db
    env_file:
      - ./backend/.env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/20250624_db.sql:/docker-entrypoint-initdb.d/20250624_db.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: job-navigator-backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./frontend
    container_name: job-navigator-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
